/**
 * Logo utilities for PDF generation
 */

// Simple SVG logo for RentRight AI - Blue shield with text
export const logoSvg = `<svg width="200" height="80" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="shieldGradient" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#3b82f6" />
      <stop offset="100%" stop-color="#1e40af" />
    </linearGradient>
  </defs>
  <!-- Shield background -->
  <path d="M40,10 L80,20 C80,50 65,65 40,70 C15,65 0,50 0,20 L40,10 Z" fill="url(#shieldGradient)" />
  <!-- Lock icon -->
  <rect x="30" y="35" width="20" height="15" rx="2" fill="white" />
  <rect x="35" y="25" width="10" height="15" rx="5" stroke="white" stroke-width="3" fill="none" />
  <!-- Text -->
  <text x="90" y="45" font-family="Arial, sans-serif" font-size="24" font-weight="bold" fill="#1e40af">RentRight AI</text>
</svg>`;

/**
 * Returns an SVG buffer from the encoded logo
 */
export function getLogoSvgBuffer(): Buffer {
  return Buffer.from(logoSvg);
}

/**
 * Default footer text for PDF documents
 */
export const footerText = 'Generated by RentRight AI - UK Tenancy Analysis Platform';

/**
 * Legal disclaimer text for PDF documents
 */
export const legalDisclaimerText = 
  "This document is an AI-generated analysis of your tenancy agreement and is provided for informational purposes only. " +
  "It is not intended to be legal advice. The analysis may not identify all issues or accurately interpret all clauses in " +
  "your agreement. RentRight AI's technology aims to highlight potential concerns, but cannot replace professional legal " +
  "counsel. For definitive advice regarding your specific situation, please consult a qualified legal professional specializing " +
  "in residential tenancy law. By using this report, you acknowledge these limitations.";